### ISSUE TITLE
Deployment target

### ISSUE THREAD

**Issue by agisboye** [tsolomko/SWCompression#1]
Is there any reason why the deployment target for iOS has to be 10.1? I can build the library just fine down to at least 8.0

**Comment by tsolomko** [comment]
I don't think there is any particular reason for the deployment target to be 10.1. The only limitation is that the latest version of Swift should be used. Currently, it is 3.1. And as far as I understand this version of Swift supports all iOS targets down to 8.0.

**Comment by agisboye** [comment]
I've submitted a PR (#2) that lowers the deployment targets for all platforms.

**Comment by tsolomko** [comment]
I've released new version (2.4.1) with your PR included.
