### ISSUE TITLE
GzipArchive.unarchive wrongMagic for short data

### ISSUE THREAD

**Issue by shawnclovie** [tsolomko/SWCompression#34]
I was use GzipArchive.archive to compress short text like "123".
Then I use GzipArchive.unarchive decompress the data, would throw error "wrongMagic" since input too short - `bitReader.bitsLeft >= 33 * 8` in GzipArchive.swift line 81.

**Comment by tsolomko** [comment]
Fixed in [4.8.1](https://github.com/tsolomko/SWCompression/releases/tag/4.8.1).

Thank you for reporting this issue.
