### ISSUE TITLE
Compiling for watchOS fails

### ISSUE THREAD

**Issue by mickeyl** [tsolomko/SWCompression#44]
I'm trying to build a library that uses `SWCompression` for watchOS, but it fails with:

```
error: The package product 'BitByteData' requires minimum platform version 5.0 for the watchOS platform, but this target supports 4.0 (in target 'SWCompression' from project 'SWCompression')
```

I noticed `BitByteData`'s released version (2.0.2) `Package.swift` not defining any `.platforms`, perhaps cutting a new release for this would fix it.

**Comment by tsolomko** [comment]
A new version of BitByteData has been released, [2.0.3](https://github.com/tsolomko/BitByteData/releases/tag/2.0.3), that should address this issue. Please don't forget to run `swift package update` (or whatever you use as your dependency manager) to get it.
