### ISSUE TITLE
Please update BitByteData dependency 

### ISSUE THREAD

**Issue by Tarasus** [tsolomko/SWCompression#56]
My project is dependent on SWCompression for zip extraction.
Please update BitByteData dependency in package.swift. 
I am getting crashes from LittleEndianByteReader.swift at line 84 from `public func uint32() -> UInt32` from BitByteData v.2.0.1
I'll submit an issue on this topic in BitByteData repository.
As I see, BitByteData is updated to 2.0.4 and `public func uint32() -> UInt32` is refactored there, which may help with future crashes.

Thanks.

**Comment by tsolomko** [comment]
Hi @Tarasus,

SWCompression does not fix the version of the BitByteData dependency to 2.0.1, so you should be able update it yourself (and I cannot update it for you). Depending on your installation method you should run one of the following to update:
1. `swift package update`
2. `pod update`
3. `carthage update`

If updating BitByteData to 2.0.4 does not fix your issue, please let me know.

**Comment by Tarasus** [comment]
Done! Thank you!

**Comment by tsolomko** [comment]
@Tarasus,

I am very sorry, I've just realized that you may be reporting an issue with SWCompression, since it should have ensured that there are sufficient bytes left to read.

Basically, SWCompression shouldn't have crashed (even through BitByteData).

If possible, could you please provide the zip file that causes this crash (if it still happens after the update)?

**Comment by tsolomko** [comment]
(I've got confused, I thought you're using BitByteData directly.)

**Comment by Tarasus** [comment]
Unfortunately I can't. The crash has happened on user's device, and obtained via TestFlight. 
Unless user reports the document manually, I can't neither debug or provide it to you.

**Comment by Tarasus** [comment]
Sorry for reopening, missclick.
