### ISSUE TITLE
Error using SPM

### ISSUE THREAD

**Issue by daSkier** [tsolomko/SWCompression#6]
Hi, 

I'm new to SWCompression, so I'm just trying to get it setup with a Swift Package Manager project and I'm running into an issue when compiling. 

```
Showing All Messages
: terminated(1): /Applications/Xcode-beta.app/Contents/Developer/usr/bin/git -C /Users/js/code/SPMTestProj/SPMTest/DerivedData/SPMTest/SourcePackages/checkouts/SWCompression submodule update --init --recursive output:
    Submodule 'Tests/Test Files' (https://github.com/tsolomko/SWCompression-Test-Files.git) registered for path 'Tests/Test Files'
    Cloning into '/Users/js/code/SPMTestProj/SPMTest/DerivedData/SPMTest/SourcePackages/checkouts/SWCompression/Tests/Test Files'...
    git: 'lfs' is not a git command. See 'git --help'.
    
    The most similar command is
    	log
    error: external filter 'git lfs smudge %f' failed 1
    error: external filter 'git lfs smudge %f' failed
    fatal: 7z/SWCompressionSourceCode.7z: smudge filter lfs failed
    Unable to checkout '543e5bc90d065c9cac22e501cff97d5c4489ce45' in submodule path 'Tests/Test Files'
```
A couple of notes: 
- I did try setting up a clean project for testing this and came to the same result
- I'm using a Swift 5.0.1 toolchain (not sure if this matters)

Thanks for any help you can provide.

**Comment by daSkier** [comment]
I forked the repo and removed the submodule and the "Test Files" folder from the project and it seems to resolve this problem. I don't know why this would be the case because I believe SPM supports submodules, but none the less it fixes the issue I was seeing. 

I haven't gotten to test functionality yet to see if anything is broken as a result, but wanted to give the update.

**Comment by tsolomko** [comment]
Hi,

What you are experiencing is the weird relationship between SPM and Git LFS. I use Git LFS to store all the example files that are used by tests. I've put them into a separate git submodule exactly because I've tried to solve this problem. I was hoping that it would work since it seemed to me that SPM kinda ignores submodules (at least, at the time when I created the submodule). Apparently, it didn't work.

Somewhat easy solution that will fix the issue for you is to install Git LFS. Ideally, I would like to find a way to somehow prevent SPM from downloading the submodule, or, at least from trying to download git-lfs'd files. Currently, I am not aware of any methods to do so.

**Comment by daSkier** [comment]
Hi @tsolomko ,

Thanks for getting back to me. I tracked this down a little bit further. It appears that if you use SPM from the command line everything works as planned. I was actually seeing the error when using SPM from the new Xcode 11 betas. 

As I said, everything is working when I use Swift/SPM from terminal, so it may be worth adding a small note about this in the project ReadMe. 

Thanks again!

**Comment by vookimedlo** [comment]
All,

I can confirm that SWCompression could be managed by the new XCode-Beta  11.0 Beta 5 flawlessly.

The only need is to link git-lfs executable to the Xcode-beta.app.
See https://stackoverflow.com/questions/57055604/xcode-11-swift-package-manager-unable-resolve-packages

Initially, you need to install git-lfs to your system. I use `brew`.
```
brew install git-lfs
```

**Comment by quentinfasquel** [comment]
@vookimedlo are you certain you get Xcode SPM working with git-lfs files ?

**Comment by vookimedlo** [comment]
@quentinfasquel 
XCode 11 beta didn't have the git-lfs executable bundled inside its app package. So, the solution I described worked for me at that time. With this in place, the SWCompression worked without any issue.
