### ISSUE TITLE
Warning during compilation: redundant public modifier

### ISSUE THREAD

**Issue by benjaminmayo** [tsolomko/SWCompression#7]
A simple issue with a simple fix. As of a recent Swift release, the compiler now diagnoses when redundant `public` modifiers exist on a type. This is causing a warning to be raised in `SWCompression`.

<img width="850" alt="Screenshot 2019-12-12 at 00 52 25" src="https://user-images.githubusercontent.com/713431/70673268-e8c3fb80-1c79-11ea-803d-26ec4bee4d08.PNG">

The warning is in file `BZip2+BlockSize.swift`. The fix would be to remove the `public` modifier on the extension (line 8). This would make the warning go away. The actual behaviour of the code would be unchanged.

**Comment by tsolomko** [comment]
I think this issue was more or less fixed in 8d0e6d5567c2349456039862565bfa493bff55e6. 

(Sorry for the long response time: it was a busy end of the year for me.)

**Comment by benjaminmayo** [comment]
Ah yea, it was fixed in that commit. It's just not in a published SPM release.

**Comment by tsolomko** [comment]
Today's small update to SWCompression (4.5.3) includes the aforementioned fix.
