### ISSUE TITLE
XCode 11 support ? 

### ISSUE THREAD

**Issue by jcbernabe1492** [tsolomko/SWCompression#8]
Hi , 

Will there be a release that will support XCode 11? Right now I'm pointing my cartfile to "develop" just to get the latest codebase that was build with swift 5.x 

Thanks!

**Comment by tsolomko** [comment]
I've released today an update to SWCompression (4.5.3) and accompanying update to BitByteData (1.4.2). It should fix incompatibility issues with Swift 5.x and recent versions of Xcode.
